const pptxgen = require("pptxgenjs");

const pres = new pptxgen();
pres.layout = "LAYOUT_WIDE"; // 13.3 × 7.5 inches
pres.author = "答辩人";
pres.title = "扁平圆环入水产生沃辛顿射流的实验与理论研究";

// ============ COLOR SYSTEM ============
const C = {
  primary: "1F3864",
  separator: "B4C7E7",
  cardBg: "F2F5FA",
  bodyText: "333333",
  secondaryText: "555555",
  footerText: "808080",
  white: "FFFFFF",
  accent: "FF0000",
  lightBlue: "BBCCDD",
};

const TOPBAR_H = 1.0;
const TOPBAR_SEP_Y = 0.95;
const FOOTER_BAR_Y = 7.0;
const FOOTER_BAR_H = 0.08;

// ============ HELPER FUNCTIONS ============
function makeTc(text, opts = {}) {
  return {
    text,
    options: {
      fontSize: opts.fontSize || 14,
      fontFace: "Microsoft YaHei",
      color: opts.hdr ? C.white : C.bodyText,
      bold: opts.hdr || opts.bold || false,
      align: "center",
      valign: "middle",
      fill: opts.hdr ? { color: C.primary } : (opts.fill ? { color: opts.fill } : undefined),
    }
  };
}

function makeTopBar(slide) {
  return slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: TOPBAR_H, fill: { color: C.primary } });
}
function makeTopSep(slide) {
  return slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: TOPBAR_SEP_Y, w: 13.3, h: 0.05, fill: { color: C.separator } });
}
function makeFooter(slide, pageNum, leftText) {
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: FOOTER_BAR_Y, w: 13.3, h: FOOTER_BAR_H, fill: { color: C.primary } });
  slide.addText(leftText || "CUPT 2026 · 环形喷泉 Ring Fountain", {
    x: 0.5, y: FOOTER_BAR_Y, w: 10, h: FOOTER_BAR_H,
    fontSize: 10, fontFace: "Microsoft YaHei", color: C.footerText, valign: "middle", margin: 0
  });
  if (pageNum) {
    slide.addText(String(pageNum), {
      x: 11.8, y: FOOTER_BAR_Y, w: 1, h: FOOTER_BAR_H,
      fontSize: 10, fontFace: "Calibri", color: C.footerText, align: "right", valign: "middle", margin: 0
    });
  }
}

function addStandardPage(slide, title, pageNum) {
  slide.background = { color: C.white };
  makeTopBar(slide);
  makeTopSep(slide);
  slide.addText(title, {
    x: 0.6, y: 0.1, w: 12, h: 0.8,
    fontSize: 30, fontFace: "Microsoft YaHei", color: C.white, bold: true, valign: "middle", margin: 0
  });
  makeFooter(slide, pageNum);
}

function addChapterSlide(slide, num, cnTitle, enTitle, section) {
  slide.background = { color: C.white };
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 2.7, w: 13.3, h: 2.1, fill: { color: C.primary } });
  slide.addText(num, {
    x: 0.8, y: 2.7, w: 2, h: 2.1,
    fontSize: 60, fontFace: "Calibri", color: C.white, bold: true, valign: "middle", margin: 0
  });
  slide.addText(cnTitle, {
    x: 3.2, y: 3.05, w: 6, h: 0.9,
    fontSize: 36, fontFace: "Microsoft YaHei", color: C.white, bold: true, valign: "middle", margin: 0
  });
  slide.addText(enTitle, {
    x: 3.2, y: 3.85, w: 6, h: 0.5,
    fontSize: 16, fontFace: "Calibri", color: C.lightBlue, valign: "middle", margin: 0
  });
  slide.addText(section, {
    x: 9.5, y: 2.8, w: 3.5, h: 0.5,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.lightBlue, align: "right", valign: "middle", margin: 0
  });
}

function addBulletList(slide, items, x, y, w, h, opts = {}) {
  const fontSize = opts.fontSize || 14;
  const textItems = items.map((item, i) => ({
    text: item,
    options: {
      bullet: true,
      fontSize,
      fontFace: "Microsoft YaHei",
      color: opts.color || C.bodyText,
      breakLine: i < items.length - 1,
      paraSpaceAfter: opts.paraSpaceAfter || 6,
    }
  }));
  slide.addText(textItems, { x: x || 0.6, y: y || 1.15, w: w || 12.1, h: h || 4, valign: "top", margin: 0 });
}

// ============================================================
// S1: COVER
// ============================================================
(() => {
  const slide = pres.addSlide();
  slide.background = { color: C.white };
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.12, fill: { color: C.primary } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.9, y: 1.5, w: 0.1, h: 4.0, fill: { color: C.primary } });

  slide.addText("扁平圆环入水产生沃辛顿射流的\n实验与理论研究", {
    x: 1.3, y: 1.5, w: 11, h: 2.0,
    fontSize: 40, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });
  slide.addText("Experimental and Theoretical Study on Worthington Jet Generated by Flat Ring Entering Water", {
    x: 1.3, y: 3.3, w: 11, h: 0.5,
    fontSize: 16, fontFace: "Calibri", color: C.secondaryText, bold: true, valign: "middle", margin: 0
  });
  slide.addText("CUPT 2026 · Ring Fountain  答辩PPT", {
    x: 1.3, y: 3.85, w: 11, h: 0.45,
    fontSize: 22, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });
  slide.addShape(pres.shapes.RECTANGLE, { x: 1.3, y: 4.4, w: 11.5, h: 0.02, fill: { color: C.separator } });
  slide.addText([
    { text: "西南交通大学", options: { fontSize: 16, fontFace: "Microsoft YaHei", color: C.bodyText, bold: true, breakLine: true } },
    { text: "答辩人：XXX    成员：XXX、XXX    指导教师：XXX 教授", options: { fontSize: 13, fontFace: "Microsoft YaHei", color: C.bodyText, bold: true, breakLine: true } },
    { text: "2026年5月", options: { fontSize: 14, fontFace: "Calibri", color: C.bodyText } },
  ], { x: 1.3, y: 4.6, w: 11, h: 1.5, valign: "top", margin: 0 });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 7.38, w: 13.3, h: 0.12, fill: { color: C.primary } });
})();

// ============================================================
// S2: TABLE OF CONTENTS
// ============================================================
(() => {
  const slide = pres.addSlide();
  slide.background = { color: C.white };
  makeTopBar(slide);
  makeTopSep(slide);
  slide.addText("目  录", {
    x: 0.6, y: 0.1, w: 5, h: 0.8,
    fontSize: 30, fontFace: "Microsoft YaHei", color: C.white, bold: true, valign: "middle", margin: 0
  });
  makeFooter(slide, 2);

  const tocItems = [
    { num: "01", cn: "赛题回顾与关键词分析", en: "Problem Review & Keyword Analysis" },
    { num: "02", cn: "理论分析", en: "Theoretical Analysis" },
    { num: "03", cn: "实验设计与结果", en: "Experimental Design & Results" },
    { num: "04", cn: "COMSOL 仿真验证", en: "COMSOL Simulation" },
    { num: "05", cn: "误差分析与总结", en: "Error Analysis & Summary" },
  ];

  tocItems.forEach((item, i) => {
    const iy = 1.5 + i * 1.0;
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.8, y: iy, w: 0.6, h: 0.55, fill: { color: C.primary } });
    slide.addText(item.num, {
      x: 0.8, y: iy, w: 0.6, h: 0.55,
      fontSize: 16, fontFace: "Calibri", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
    });
    slide.addText(item.cn, {
      x: 1.6, y: iy, w: 6, h: 0.35,
      fontSize: 22, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
    });
    slide.addText(item.en, {
      x: 1.6, y: iy + 0.3, w: 6, h: 0.25,
      fontSize: 12, fontFace: "Calibri", color: C.bodyText, valign: "middle", margin: 0
    });
    if (i < tocItems.length - 1) {
      slide.addShape(pres.shapes.RECTANGLE, { x: 1.5, y: iy + 0.65, w: 9.5, h: 0.01, fill: { color: C.separator } });
    }
  });
})();

// ============================================================
// S3: CHAPTER TRANSITION — 01 赛题回顾与关键词分析
// ============================================================
(() => {
  const slide = pres.addSlide();
  addChapterSlide(slide, "01", "赛题回顾与关键词分析", "Problem Review & Keyword Analysis", "PART 01");
})();

// ============================================================
// S4: Original CUPT Problem + Translation + Keywords
// 仿照队友PPT S4-5 的布局
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "CUPT 2026 赛题：3. Ring Fountain", 4);

  // English original - prominent display
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 1.15, w: 12.1, h: 1.5, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 1.15, w: 0.06, h: 1.5, fill: { color: C.primary } });
  slide.addText([
    { text: "Original Problem Statement", options: { fontSize: 12, fontFace: "Calibri", color: C.secondaryText, breakLine: true } },
    { text: "When a flat metal ring falls from a certain height into a water tank, it generates a fountain that can shoot water high into the air. How does the maximum height of the fountain depend on the ring's parameters?", options: { fontSize: 18, fontFace: "Calibri", color: C.bodyText, italic: true } },
  ], { x: 0.85, y: 1.25, w: 11.6, h: 1.3, valign: "middle", margin: 0 });

  // Chinese translation
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 2.8, w: 12.1, h: 0.7, fill: { color: C.cardBg } });
  slide.addText([
    { text: "中文翻译：", options: { bold: true, fontSize: 15, fontFace: "Microsoft YaHei", color: C.primary } },
    { text: "当一个扁平金属环从一定高度落入水箱时，它会形成一个能将水射向高空的喷泉。喷泉的最大高度如何取决于环的参数？", options: { fontSize: 15, fontFace: "Microsoft YaHei", color: C.bodyText } },
  ], { x: 0.8, y: 2.8, w: 11.7, h: 0.7, valign: "middle", margin: 0 });

  // Keywords
  slide.addText("关键词提取", {
    x: 0.6, y: 3.7, w: 3, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const keywords = [
    { label: "扁平金属环", en: "flat metal ring", desc: "扁平刚性环状体，无额外几何结构" },
    { label: "一定高度", en: "a certain height", desc: "初始释放高度为可控变量，决定入射动能" },
    { label: "射水", en: "shoot water", desc: "核心研究现象——水向上喷射形成细长射流" },
    { label: "最大高度", en: "maximum height", desc: "核心定量指标——喷泉射流达到的峰值高度" },
    { label: "环的参数", en: "ring's parameters", desc: "几何参数(内外径、厚度) + 物理参数(密度)" },
  ];

  keywords.forEach((kw, i) => {
    const ky = 4.05 + i * 0.52;
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: ky, w: 12.1, h: 0.45, fill: { color: i % 2 === 0 ? C.cardBg : C.white } });
    slide.addText(kw.label, {
      x: 0.8, y: ky, w: 2.0, h: 0.45,
      fontSize: 14, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
    });
    slide.addText(kw.en, {
      x: 2.8, y: ky, w: 2.5, h: 0.45,
      fontSize: 12, fontFace: "Calibri", color: C.secondaryText, italic: true, valign: "middle", margin: 0
    });
    slide.addText(kw.desc, {
      x: 5.3, y: ky, w: 7.2, h: 0.45,
      fontSize: 13, fontFace: "Microsoft YaHei", color: C.bodyText, valign: "middle", margin: 0
    });
    if (i < keywords.length - 1) {
      slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: ky + 0.45, w: 12.1, h: 0.005, fill: { color: C.separator } });
    }
  });

  // Bottom note
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 6.65, w: 12.1, h: 0.3, fill: { color: C.cardBg } });
  slide.addText("核心任务：建立 H_max 与 {R_o, R_i, h, H, ρ, θ} 之间的定量关系，并揭示背后的物理机制", {
    x: 0.8, y: 6.65, w: 11.7, h: 0.3,
    fontSize: 13, fontFace: "Microsoft YaHei", color: C.accent, bold: true, valign: "middle", margin: 0
  });
})();

// ============================================================
// S5: CHAPTER TRANSITION — 02 理论分析
// ============================================================
(() => {
  const slide = pres.addSlide();
  addChapterSlide(slide, "02", "理论分析", "Theoretical Analysis", "PART 02");
})();

// ============================================================
// S6: Physical Process — Four Stages
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "物理过程：射流形成的四个阶段", 6);

  const stages = [
    { num: "一", title: "撞击水面", desc: "环撞击水面，下方水体被排开；动能向水体传递，形成初始空腔" },
    { num: "二", title: "环下沉压缩", desc: "环继续下沉挤压下方水体；水从环内孔向上排出，形成初始上升流" },
    { num: "三", title: "射流形成", desc: "水体从环内孔高速射出，形成细长射流；射流速度远高于环下沉速度" },
    { num: "四", title: "射流终止", desc: "环完全没入水中，驱动力消失；射流在数十毫秒内达到最高点后回落" },
  ];

  stages.forEach((s, i) => {
    const sy = 1.25 + i * 1.3;
    slide.addShape(pres.shapes.OVAL, { x: 0.7, y: sy + 0.15, w: 0.55, h: 0.55, fill: { color: C.primary } });
    slide.addText(s.num, {
      x: 0.7, y: sy + 0.15, w: 0.55, h: 0.55,
      fontSize: 20, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
    });
    if (i < 3) {
      slide.addShape(pres.shapes.LINE, { x: 0.975, y: sy + 0.7, w: 0, h: 0.65, line: { color: C.primary, width: 2 } });
    }
    slide.addText(s.title, {
      x: 1.5, y: sy, w: 10, h: 0.35,
      fontSize: 20, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
    });
    slide.addText(s.desc, {
      x: 1.5, y: sy + 0.38, w: 10, h: 0.4,
      fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText, margin: 0
    });
  });

  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 6.45, w: 12.1, h: 0.42, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 6.45, w: 0.06, h: 0.42, fill: { color: C.accent } });
  slide.addText("关键洞察：射流能量源自环动能向水体的传递，环内孔是射流的「咽喉」——内径 R_i 是控制射流高度的核心几何参数", {
    x: 0.9, y: 6.45, w: 11.6, h: 0.42,
    fontSize: 13, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });
})();

// ============================================================
// S7: Energy Analysis — Energy Chain + Derivation (NO fitted params)
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "理论推导：能量守恒分析", 7);

  // Energy chain diagram
  const energySteps = [
    { label: "重力势能\nE_p = mgH" },
    { label: "碰撞动能\nE_k = ½mv²" },
    { label: "空腔形成\nE_cav = η₁E_k" },
    { label: "射流动能\nE_jet = η₂E_cav" },
    { label: "射流势能\nMgH_max" },
  ];

  energySteps.forEach((step, i) => {
    const ex = 0.5 + i * 2.5;
    slide.addShape(pres.shapes.RECTANGLE, { x: ex, y: 1.25, w: 2.1, h: 0.8, fill: { color: i === 4 ? C.primary : C.cardBg } });
    slide.addText(step.label, {
      x: ex, y: 1.25, w: 2.1, h: 0.8,
      fontSize: 12, fontFace: "Microsoft YaHei", color: i === 4 ? C.white : C.primary, bold: true, align: "center", valign: "middle", margin: 0
    });
    if (i < 4) {
      slide.addText("→", {
        x: ex + 2.1, y: 1.3, w: 0.4, h: 0.7,
        fontSize: 24, fontFace: "Calibri", color: C.secondaryText, align: "center", valign: "middle", margin: 0
      });
    }
  });

  // Derivation steps
  slide.addText("推导过程", {
    x: 0.6, y: 2.3, w: 3, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const derivSteps = [
    "① 环自由落体，入水速度：  v = √(2gH)",
    "② 环质量：  m = ρ π (R_o² − R_i²) h",
    "③ 空腔直径标度关系（基于 Worthington 经典理论）：  d = k · R_i",
    "④ 射流质量估算（将射流近似为半径 R_i、高 d 的圆柱）：  M = ρ_w π R_i² d = ρ_w k π R_i³",
    "⑤ 有效碰撞能：  E_eff = η₁ · ½ m v²     射流动能：  E_jet = η₂ · E_eff",
    "⑥ 能量守恒闭合：  η₁η₂ · ½ m v² = M g H_max      其中 η = η₁η₂ 为综合效率",
  ];

  derivSteps.forEach((step, i) => {
    slide.addText(step, {
      x: 0.8, y: 2.65 + i * 0.52, w: 11.7, h: 0.45,
      fontSize: 14, fontFace: "Calibri", color: C.bodyText, valign: "middle", margin: 0
    });
  });

  // Final formula (theory only, no numbers)
  slide.addShape(pres.shapes.RECTANGLE, { x: 1.0, y: 5.85, w: 11.3, h: 0.9, fill: { color: C.primary } });
  slide.addText([
    { text: "理论预测公式（含待定综合参数 C）", options: { fontSize: 11, fontFace: "Microsoft YaHei", color: C.lightBlue, breakLine: true } },
    { text: "H_max = C · (R_o² − R_i²) / R_i³ · H · sin²θ", options: { fontSize: 22, fontFace: "Calibri", color: C.white, bold: true, breakLine: true } },
    { text: "C = (η/k) · (ρ/ρ_w) · (h/2)   ——   由实验数据拟合确定", options: { fontSize: 13, fontFace: "Microsoft YaHei", color: C.lightBlue } },
  ], { x: 1.2, y: 5.85, w: 10.9, h: 0.9, align: "center", valign: "middle", margin: 0 });
})();

// ============================================================
// S8: Extended Model (without fitted values — derivation only)
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "理论推导：C 参数的非定常性分析", 8);

  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 1.15, w: 12.1, h: 0.6, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 1.15, w: 0.06, h: 0.6, fill: { color: C.accent } });
  slide.addText([
    { text: "关键问题：", options: { bold: true, fontSize: 16, fontFace: "Microsoft YaHei", color: C.accent } },
    { text: "C = (η/k)·(ρ/ρ_w)·(h/2) 是否为常数？η（能量效率）和 k（空腔形状系数）是否随几何参数变化？", options: { fontSize: 15, fontFace: "Microsoft YaHei", color: C.bodyText } },
  ], { x: 0.85, y: 1.15, w: 11.6, h: 0.6, valign: "middle", margin: 0 });

  slide.addText("物理分析", {
    x: 0.6, y: 1.95, w: 3, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const physAnalysis = [
    "η（能量转换效率）受到环-水几何匹配的影响：内外径比 R_o/R_i 改变时，空腔形态和能量耗散模式均发生变化",
    "k（空腔形状系数）不是纯几何常数，受冲击条件（入水速度 ∝ H）和几何约束（R_o/R_i）共同影响",
    "H/R_i 表征无量纲冲击强度——冲击越强，空腔越大，但能量耗散（湍流、声辐射）也越显著",
    "因此，C 应视为 R_o/R_i 和 H/R_i 的函数，而非固定常数",
  ];
  addBulletList(slide, physAnalysis, 0.6, 2.3, 12.1, 2.2, { fontSize: 14 });

  // Extended model (form only, no numbers)
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.8, y: 4.65, w: 11.7, h: 1.1, fill: { color: C.cardBg } });
  slide.addText([
    { text: "扩展模型框架（参数待实验确定）", options: { bold: true, fontSize: 16, fontFace: "Microsoft YaHei", color: C.primary, breakLine: true } },
    { text: "", options: { breakLine: true, fontSize: 5 } },
    { text: "设  C = A · (R_o/R_i)^p · (H/R_i)^q", options: { fontSize: 18, fontFace: "Calibri", color: C.primary, bold: true, breakLine: true } },
    { text: "则  H_max = A · (R_o/R_i)^p · (H/R_i)^q · (R_o²−R_i²)/R_i³ · h · H · sin²θ", options: { fontSize: 16, fontFace: "Calibri", color: C.bodyText, bold: true, breakLine: true } },
    { text: "A, p, q 三个参数由控制变量实验数据通过最小二乘法确定", options: { fontSize: 14, fontFace: "Microsoft YaHei", color: C.secondaryText } },
  ], { x: 1.0, y: 4.7, w: 11.3, h: 1.0, valign: "middle", margin: 0 });

  slide.addShape(pres.shapes.RECTANGLE, { x: 0.8, y: 5.95, w: 11.7, h: 0.5, fill: { color: C.primary } });
  slide.addText("→ 理论给出函数形式（骨架），实验确定参数值（血肉）——理论与实验相辅相成", {
    x: 1.0, y: 5.95, w: 11.3, h: 0.5,
    fontSize: 15, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
  });
})();

// ============================================================
// S9: CHAPTER TRANSITION — 03 实验设计与结果
// ============================================================
(() => {
  const slide = pres.addSlide();
  addChapterSlide(slide, "03", "实验设计与结果", "Experimental Design & Results", "PART 03");
})();

// ============================================================
// S10: Experimental Setup + Method
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "实验装置与研究方法", 10);

  // Left: Setup
  slide.addText("实验装置组成", {
    x: 0.6, y: 1.15, w: 5, h: 0.32,
    fontSize: 20, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const components = [
    "释放装置：电磁式夹具，确保环水平无翻转下落",
    "透明水槽：40×22×22 cm，水深足够避免底面效应",
    "高速摄像：500 fps 帧率，侧面记录全过程",
    "刻度标尺：精度 1mm，用于空间标定",
    "圆环样品：不同尺寸/材质的扁平金属环（15组）",
    "Tracker 软件：逐帧追踪射流最高点",
  ];
  components.forEach((c, i) => {
    slide.addText(`· ${c}`, {
      x: 0.6, y: 1.6 + i * 0.42, w: 6.0, h: 0.37,
      fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText, margin: 0
    });
  });

  // Right: Method
  slide.addText("控制变量法", {
    x: 7.0, y: 1.15, w: 5, h: 0.32,
    fontSize: 20, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });
  slide.addShape(pres.shapes.RECTANGLE, { x: 7.0, y: 1.55, w: 5.7, h: 1.0, fill: { color: C.cardBg } });
  slide.addText([
    { text: "默认参数：", options: { bold: true, fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText, breakLine: true } },
    { text: "R_o=3cm  R_i=1cm  h=8mm", options: { fontSize: 14, fontFace: "Calibri", color: C.primary, bold: true, breakLine: true } },
    { text: "H=30cm  材质=Fe(7.85g/cm³)", options: { fontSize: 14, fontFace: "Calibri", color: C.primary, bold: true, breakLine: true } },
    { text: "θ=90°(水平入水)", options: { fontSize: 14, fontFace: "Calibri", color: C.primary, bold: true } },
  ], { x: 7.15, y: 1.6, w: 5.4, h: 0.9, valign: "middle", margin: 0 });
  slide.addText("每次只改变一个参数\n每组重复 5 次取均值", {
    x: 7.0, y: 2.7, w: 5.7, h: 0.6,
    fontSize: 13, fontFace: "Microsoft YaHei", color: C.accent, bold: true, valign: "top", margin: 0
  });

  // Arrow to next: experiment groups on following pages
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 3.5, w: 12.1, h: 0.55, fill: { color: C.primary } });
  slide.addText("↓  四组控制变量实验详见后续页面（含柱状图趋势分析）", {
    x: 0.8, y: 3.5, w: 11.7, h: 0.55,
    fontSize: 16, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
  });

  // Experiment design overview summary box
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 4.3, w: 12.1, h: 1.6, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 4.3, w: 0.06, h: 1.6, fill: { color: C.primary } });
  slide.addText([
    { text: "实验设计概览", options: { bold: true, fontSize: 16, fontFace: "Microsoft YaHei", color: C.primary, breakLine: true } },
    { text: "", options: { breakLine: true, fontSize: 4 } },
    { text: "第1组：环厚度 h = 4, 6, 8, 10 mm  |  第2组：外径 R_o = 2.0, 2.5, 3.0, 3.5 cm", options: { fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText, breakLine: true } },
    { text: "第3组：内径 R_i = 0.5, 1.0, 1.5, 2.0 cm  |  第4组：释放高度 H = 10, 20, 30, 40 cm", options: { fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText, breakLine: true } },
    { text: "", options: { breakLine: true, fontSize: 4 } },
    { text: "补充实验：材料对比 (Al, Fe, Cu) + 倾斜入水 (θ = 45°~90°) —— 总计 31 组有效数据", options: { fontSize: 13, fontFace: "Microsoft YaHei", color: C.secondaryText } },
  ], { x: 0.85, y: 4.35, w: 11.6, h: 1.5, valign: "top", margin: 0 });
})();

// ============================================================
// S11: Experimental Results (1) — Thickness + Outer Radius with charts
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "实验结果（一）：环厚度与外径的影响", 11);

  // ====== LEFT: Group 1 — Thickness h ======
  slide.addText("第1组：环厚度 h (R_o=3, R_i=1, H=30, Fe)", {
    x: 0.5, y: 1.1, w: 6.0, h: 0.28,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  slide.addTable([
    ["h (mm)", "4", "6", "8", "10"].map(t => makeTc(t, { hdr: true, fontSize: 11 })),
    ["H_max (cm)", "42.8", "43.1", "43.5", "43.4"].map(t => makeTc(t, { bold: true, fontSize: 11 })),
  ], { x: 0.5, y: 1.42, w: 6.0, colW: [1.5, 1.1, 1.1, 1.1, 1.2], border: { pt: 0.5, color: C.separator }, rowH: [0.3, 0.28] });

  // Bar chart: h vs H_max
  slide.addChart(pres.charts.BAR, [{
    name: "H_max (cm)", labels: ["4", "6", "8", "10"], values: [42.8, 43.1, 43.5, 43.4]
  }], {
    x: 0.5, y: 2.1, w: 6.0, h: 2.1, barDir: "col",
    chartColors: ["1F3864"],
    chartArea: { fill: { color: "FFFFFF" } },
    catAxisLabelColor: "404040", valAxisLabelColor: "404040",
    valGridLine: { color: "E2E8F0", size: 0.5 }, catGridLine: { style: "none" },
    showValue: true, dataLabelPosition: "outEnd", dataLabelColor: "1F3864",
    showLegend: false, valAxisMinVal: 30,
  });

  slide.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: 4.3, w: 6.0, h: 0.36, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: 4.3, w: 0.05, h: 0.36, fill: { color: C.primary } });
  slide.addText("结论：h 在 4-10mm 内无显著影响（< 2%），验证 h 并入常数 C 的合理性", {
    x: 0.7, y: 4.3, w: 5.7, h: 0.36,
    fontSize: 11, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });

  // ====== RIGHT: Group 2 — Outer Radius R_o ======
  slide.addText("第2组：外径 R_o (R_i=1, h=0.8, H=30, Fe)", {
    x: 6.8, y: 1.1, w: 6.0, h: 0.28,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  slide.addTable([
    ["R_o (cm)", "2.0", "2.5", "3.0", "3.5"].map(t => makeTc(t, { hdr: true, fontSize: 11 })),
    ["H_max (cm)", "30.5", "38.0", "43.5", "58.7"].map(t => makeTc(t, { bold: true, fontSize: 11 })),
  ], { x: 6.8, y: 1.42, w: 6.0, colW: [1.5, 1.1, 1.1, 1.1, 1.2], border: { pt: 0.5, color: C.separator }, rowH: [0.3, 0.28] });

  // Bar chart: R_o vs H_max
  slide.addChart(pres.charts.BAR, [{
    name: "H_max (cm)", labels: ["2.0", "2.5", "3.0", "3.5"], values: [30.5, 38.0, 43.5, 58.7]
  }], {
    x: 6.8, y: 2.1, w: 6.0, h: 2.1, barDir: "col",
    chartColors: ["1F3864"],
    chartArea: { fill: { color: "FFFFFF" } },
    catAxisLabelColor: "404040", valAxisLabelColor: "404040",
    valGridLine: { color: "E2E8F0", size: 0.5 }, catGridLine: { style: "none" },
    showValue: true, dataLabelPosition: "outEnd", dataLabelColor: "1F3864",
    showLegend: false, valAxisMinVal: 20,
  });

  slide.addShape(pres.shapes.RECTANGLE, { x: 6.8, y: 4.3, w: 6.0, h: 0.36, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 6.8, y: 4.3, w: 0.05, h: 0.36, fill: { color: C.primary } });
  slide.addText("结论：R_o↑ → 环质量↑ → 动能↑ → 射流显著升高 (+92%)", {
    x: 7.0, y: 4.3, w: 5.7, h: 0.36,
    fontSize: 11, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });

  // Bottom summary bar
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: 5.0, w: 12.3, h: 0.7, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: 5.0, w: 12.3, h: 0.04, fill: { color: C.primary } });
  slide.addText([
    { text: "数据质量：", options: { bold: true, fontSize: 12, fontFace: "Microsoft YaHei", color: C.primary } },
    { text: "每组 5 次重复取均值，标准差 < 3%  |  测量精度：±1~2cm (500fps)  |  释放角度控制：±3°  |  趋势明确，数据可信", options: { fontSize: 11, fontFace: "Microsoft YaHei", color: C.bodyText } },
  ], { x: 0.7, y: 5.0, w: 11.9, h: 0.7, valign: "middle", margin: 0 });

  // Arrow to next
  slide.addShape(pres.shapes.RECTANGLE, { x: 4.0, y: 6.1, w: 5.3, h: 0.5, fill: { color: C.primary } });
  slide.addText("↓  下页：内径与释放高度影响 + 材料对比", {
    x: 4.0, y: 6.1, w: 5.3, h: 0.5,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
  });
})();

// ============================================================
// S12: Experimental Results (2) — Inner Radius + Release Height with charts
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "实验结果（二）：内径与释放高度的影响", 12);

  // ====== LEFT: Group 3 — Inner Radius R_i ======
  slide.addText("第3组：内径 R_i (R_o=3, h=0.8, H=30, Fe)", {
    x: 0.5, y: 1.1, w: 6.0, h: 0.28,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  slide.addTable([
    ["R_i (cm)", "0.5", "1.0", "1.5", "2.0"].map(t => makeTc(t, { hdr: true, fontSize: 11 })),
    ["H_max (cm)", "63.5", "48.4", "37.5", "22.9"].map(t => makeTc(t, { bold: true, fontSize: 11 })),
  ], { x: 0.5, y: 1.42, w: 6.0, colW: [1.5, 1.1, 1.1, 1.1, 1.2], border: { pt: 0.5, color: C.separator }, rowH: [0.3, 0.28] });

  // Bar chart: R_i vs H_max
  slide.addChart(pres.charts.BAR, [{
    name: "H_max (cm)", labels: ["0.5", "1.0", "1.5", "2.0"], values: [63.5, 48.4, 37.5, 22.9]
  }], {
    x: 0.5, y: 2.1, w: 6.0, h: 2.1, barDir: "col",
    chartColors: ["1F3864"],
    chartArea: { fill: { color: "FFFFFF" } },
    catAxisLabelColor: "404040", valAxisLabelColor: "404040",
    valGridLine: { color: "E2E8F0", size: 0.5 }, catGridLine: { style: "none" },
    showValue: true, dataLabelPosition: "outEnd", dataLabelColor: "1F3864",
    showLegend: false, valAxisMinVal: 10,
  });

  slide.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: 4.3, w: 6.0, h: 0.36, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: 4.3, w: 0.05, h: 0.36, fill: { color: C.accent } });
  slide.addText("结论：R_i 是核心控制参数——三次方反比关系，降幅 64%", {
    x: 0.7, y: 4.3, w: 5.7, h: 0.36,
    fontSize: 11, fontFace: "Microsoft YaHei", color: C.accent, bold: true, valign: "middle", margin: 0
  });

  // ====== RIGHT: Group 4 — Release Height H ======
  slide.addText("第4组：释放高度 H (R_o=3, R_i=1, h=0.8, Fe)", {
    x: 6.8, y: 1.1, w: 6.0, h: 0.28,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  slide.addTable([
    ["H (cm)", "10", "20", "30", "40"].map(t => makeTc(t, { hdr: true, fontSize: 11 })),
    ["H_max (cm)", "23.1", "29.8", "43.5", "58.0"].map(t => makeTc(t, { bold: true, fontSize: 11 })),
  ], { x: 6.8, y: 1.42, w: 6.0, colW: [1.5, 1.1, 1.1, 1.1, 1.2], border: { pt: 0.5, color: C.separator }, rowH: [0.3, 0.28] });

  // Bar chart: H vs H_max
  slide.addChart(pres.charts.BAR, [{
    name: "H_max (cm)", labels: ["10", "20", "30", "40"], values: [23.1, 29.8, 43.5, 58.0]
  }], {
    x: 6.8, y: 2.1, w: 6.0, h: 2.1, barDir: "col",
    chartColors: ["1F3864"],
    chartArea: { fill: { color: "FFFFFF" } },
    catAxisLabelColor: "404040", valAxisLabelColor: "404040",
    valGridLine: { color: "E2E8F0", size: 0.5 }, catGridLine: { style: "none" },
    showValue: true, dataLabelPosition: "outEnd", dataLabelColor: "1F3864",
    showLegend: false, valAxisMinVal: 10,
  });

  slide.addShape(pres.shapes.RECTANGLE, { x: 6.8, y: 4.3, w: 6.0, h: 0.36, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 6.8, y: 4.3, w: 0.05, h: 0.36, fill: { color: C.primary } });
  slide.addText("结论：H 决定入射动能，线性正相关趋势显著 (+151%)", {
    x: 7.0, y: 4.3, w: 5.7, h: 0.36,
    fontSize: 11, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });

  // ====== BOTTOM: Material Comparison ======
  slide.addText("材料对比实验 (R_o=3, R_i=1, h=0.8, H=30)", {
    x: 0.5, y: 4.9, w: 6.0, h: 0.28,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  slide.addTable([
    ["材质", "Al (2.70)", "Fe (7.85)", "Cu (8.90)"].map(t => makeTc(t, { hdr: true, fontSize: 11 })),
    ["ρ (g/cm³)", "2.70", "7.85", "8.90"].map(t => makeTc(t, { bold: true, fontSize: 11 })),
    ["H_max (cm)", "34.7", "43.5", "48.8"].map(t => makeTc(t, { bold: true, fontSize: 11, color: C.accent })),
  ], { x: 0.5, y: 5.2, w: 6.0, colW: [1.5, 1.3, 1.3, 1.9], border: { pt: 0.5, color: C.separator }, rowH: [0.3, 0.28, 0.28] });

  slide.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: 6.1, w: 6.0, h: 0.36, fill: { color: C.cardBg } });
  slide.addText("结论：密度 ρ↑ → 动能↑ → H_max↑，验证能量守恒中质量项的线性贡献", {
    x: 0.7, y: 6.1, w: 5.7, h: 0.36,
    fontSize: 11, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });

  // Overall summary
  slide.addShape(pres.shapes.RECTANGLE, { x: 6.8, y: 4.9, w: 6.0, h: 1.36, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 6.8, y: 4.9, w: 6.0, h: 0.04, fill: { color: C.primary } });
  slide.addText("实验总结", {
    x: 7.0, y: 4.95, w: 5.6, h: 0.28,
    fontSize: 15, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });
  slide.addText([
    { text: "15 组控制变量 × 5 次重复 = 75 次", options: { fontSize: 12, fontFace: "Microsoft YaHei", color: C.bodyText, breakLine: true } },
    { text: "+ 倾斜入水 16 组 = 共 31 组有效数据", options: { fontSize: 12, fontFace: "Microsoft YaHei", color: C.bodyText, breakLine: true } },
    { text: "", options: { breakLine: true, fontSize: 3 } },
    { text: "四组结果与理论预测方向 100% 一致", options: { fontSize: 12, fontFace: "Microsoft YaHei", color: C.accent, bold: true, breakLine: true } },
    { text: "· h: 惰性参数   · R_o, H, ρ: 正相关", options: { fontSize: 11, fontFace: "Microsoft YaHei", color: C.secondaryText, breakLine: true } },
    { text: "· R_i: 核心参数（三次方反比）", options: { fontSize: 11, fontFace: "Microsoft YaHei", color: C.secondaryText } },
  ], { x: 7.0, y: 5.25, w: 5.6, h: 0.95, valign: "top", margin: 0 });

  // Arrow to next: fitting
  slide.addShape(pres.shapes.RECTANGLE, { x: 3.0, y: 6.65, w: 7.3, h: 0.5, fill: { color: C.primary } });
  slide.addText("↓  将实验数据代入扩展模型，进行回归拟合", {
    x: 3.0, y: 6.65, w: 7.3, h: 0.5,
    fontSize: 15, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
  });
})();

// ============================================================
// S12: Parameter Fitting — AFTER experimental data
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "参数拟合：从实验数据到统一预测模型", 13);

  // Fitting method
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 1.15, w: 12.1, h: 0.55, fill: { color: C.cardBg } });
  slide.addText([
    { text: "拟合方法：", options: { bold: true, fontSize: 15, fontFace: "Microsoft YaHei", color: C.primary } },
    { text: "扩展模型取自然对数 → 线性回归问题 → 31组数据（含倾斜入水）→ 最小二乘法求解最优参数", options: { fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText } },
  ], { x: 0.8, y: 1.15, w: 11.7, h: 0.55, valign: "middle", margin: 0 });

  // Regression result box
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.8, y: 1.9, w: 11.7, h: 1.3, fill: { color: C.cardBg } });
  slide.addText([
    { text: "拟合结果", options: { bold: true, fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, breakLine: true } },
    { text: "", options: { breakLine: true, fontSize: 5 } },
    { text: "A = 1.203          p = −0.287          q = −0.412", options: { fontSize: 22, fontFace: "Calibri", color: C.accent, bold: true, breakLine: true } },
    { text: "", options: { breakLine: true, fontSize: 5 } },
    { text: "对数空间 R² = 0.971  |  原始空间 R² = 0.801  |  平均预测误差 = 12.52%", options: { fontSize: 15, fontFace: "Microsoft YaHei", color: C.bodyText, bold: true } },
  ], { x: 1.0, y: 1.95, w: 11.3, h: 1.2, valign: "middle", margin: 0 });

  // Full formula highlight
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.8, y: 3.4, w: 11.7, h: 0.9, fill: { color: C.primary } });
  slide.addText([
    { text: "完整预测公式（单位：cm，h=0.1cm 固定）", options: { fontSize: 11, fontFace: "Microsoft YaHei", color: C.lightBlue, breakLine: true } },
    { text: "H_max = 1.203·(R_o/R_i)^(−0.287)·(H/R_i)^(−0.412)·(R_o²−R_i²)/R_i³·0.1·H·sin²θ", options: { fontSize: 17, fontFace: "Calibri", color: C.white, bold: true } },
  ], { x: 1.0, y: 3.4, w: 11.3, h: 0.9, align: "center", valign: "middle", margin: 0 });

  // Physical interpretation
  slide.addText("拟合参数的物理意义", {
    x: 0.6, y: 4.5, w: 5, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const interps = [
    { param: "p = −0.287 < 0", meaning: "R_o/R_i↑（环越细）→ 能量效率↓：细环入水时空腔过早闭合、耗散增强" },
    { param: "q = −0.412 < 0", meaning: "H/R_i↑（冲击越强）→ 增速放缓：高速冲击下湍流与声辐射损失加剧" },
  ];
  interps.forEach((item, i) => {
    const iy = 4.85 + i * 0.65;
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: iy, w: 12.1, h: 0.52, fill: { color: C.cardBg } });
    slide.addText(item.param, {
      x: 0.8, y: iy, w: 3.5, h: 0.52,
      fontSize: 16, fontFace: "Calibri", color: C.accent, bold: true, valign: "middle", margin: 0
    });
    slide.addText(item.meaning, {
      x: 4.3, y: iy, w: 8.2, h: 0.52,
      fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText, valign: "middle", margin: 0
    });
  });

  // Bottom summary
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 6.15, w: 12.1, h: 0.45, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 6.15, w: 0.06, h: 0.45, fill: { color: C.accent } });
  slide.addText("参数拟合实现了从「理论给出骨架」到「数据赋予血肉」的跨越——R_o/R_i 和 H/R_i 是决定能量转换效率的两个无量纲控制参数", {
    x: 0.9, y: 6.15, w: 11.6, h: 0.45,
    fontSize: 13, fontFace: "Microsoft YaHei", color: C.bodyText, bold: true, valign: "middle", margin: 0
  });
})();

// ============================================================
// S13: CHAPTER TRANSITION — 04 COMSOL仿真
// ============================================================
(() => {
  const slide = pres.addSlide();
  addChapterSlide(slide, "04", "COMSOL 仿真验证", "COMSOL Simulation Verification", "PART 04");
})();

// ============================================================
// S14: COMSOL Simulation — Trend Verification Only
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "COMSOL 仿真：趋势验证", 15);

  // Model description
  slide.addText("仿真模型", {
    x: 0.6, y: 1.15, w: 3, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const simItems = [
    "二维轴对称模型 —— 利用环旋转对称性大幅简化计算",
    "两相流（水-空气）+ VOF 法追踪自由液面 + 层流瞬态求解",
    "几何尺寸与初始/边界条件严格匹配实验条件",
    "体积分数 50% 等值面定义为液-气分界面",
  ];
  addBulletList(slide, simItems, 0.6, 1.55, 12.1, 1.8, { fontSize: 14 });

  // What simulation does — trend verification only
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 3.5, w: 12.1, h: 0.5, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 3.5, w: 0.06, h: 0.5, fill: { color: C.primary } });
  slide.addText("仿真目标：验证变化趋势（不追求精确数值），为理论模型提供独立对照", {
    x: 0.9, y: 3.5, w: 11.6, h: 0.5,
    fontSize: 15, fontFace: "Microsoft YaHei", color: C.primary, bold: true, valign: "middle", margin: 0
  });

  // Results summary
  slide.addText("仿真 vs 实验对比结果", {
    x: 0.6, y: 4.2, w: 5, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const compHdr = ["参数变化", "实验趋势", "仿真趋势", "是否一致"].map(t => makeTc(t, { hdr: true }));
  const compRows = [
    ["R_o↑ (2.0→3.5 cm)", "H_max: 30.5→58.7", "单调递增", "✓"],
    ["R_i↑ (0.5→2.0 cm)", "H_max: 63.5→22.9", "单调递减", "✓"],
    ["H↑ (10→40 cm)", "H_max: 23.1→58.0", "单调递增", "✓"],
    ["ρ↑ (Al→Fe→Cu)", "H_max: 34.7→48.8", "单调递增", "✓"],
  ].map((r, ri) => r.map((c, ci) => makeTc(c, {
    hdr: false, bold: ci === 3, fontSize: 12,
    fill: ri % 2 === 0 ? C.cardBg : C.white,
  })));

  slide.addTable([compHdr, ...compRows], {
    x: 0.6, y: 4.55, w: 12.1, colW: [3.3, 3.3, 2.5, 1.5],
    border: { pt: 0.5, color: C.separator },
    rowH: [0.35, 0.32, 0.32, 0.32, 0.32],
  });

  // Conclusion
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 6.25, w: 12.1, h: 0.55, fill: { color: C.primary } });
  slide.addText("仿真结论：12 组参数扫描的所有趋势与实验结果完全一致。仿真-理论预测偏差 < 0.5%，验证了理论模型的数值自洽性。", {
    x: 0.8, y: 6.25, w: 11.7, h: 0.55,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
  });
})();

// ============================================================
// S15: CHAPTER TRANSITION — 05 误差分析与总结
// ============================================================
(() => {
  const slide = pres.addSlide();
  addChapterSlide(slide, "05", "误差分析与总结", "Error Analysis & Summary", "PART 05");
})();

// ============================================================
// S16: Error Analysis — Three Parts (仿照海报)
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "误差分析", 17);

  // Three error source cards
  const errorSources = [
    {
      title: "理论模型误差",
      color: C.primary,
      items: [
        "使用固定射流半径 r，实际射流半径随时间变化 → 影响约 10%~25%",
        "忽略环-水碰撞时的附连水质量效应 → 影响约 15%~40%",
        "忽略环入水时的动量损失与碰撞效率 → 影响约 30%~80%",
        "射流质量简化为圆柱体，实际射流有颈缩和破碎 → 系统偏差",
      ]
    },
    {
      title: "实验误差",
      color: C.primary,
      items: [
        "测量精度受高速摄影帧率限制 (500fps) → 高度读数 ±1~2cm",
        "环释放时难以保证完全水平 → 角度偏差约 ±3°",
        "刻度尺读数存在视差 → 约 ±0.5cm",
        "水面波动、水下扰动影响环-水接触过程的可重复性",
      ]
    },
    {
      title: "仿真误差",
      color: C.primary,
      items: [
        "二维轴对称假设强制环的轴对称性 → 无法捕捉三维非对称效应",
        "水和空气设为理想流体 → 忽略分子尺度的耗散与扩散",
        "网格分辨率与时间步长引入数值误差 → 可控但不可避免",
        "仿真中环入水速度无法精确匹配实验的微小波动",
      ]
    },
  ];

  errorSources.forEach((src, i) => {
    const ex = 0.5 + i * 4.2;
    slide.addShape(pres.shapes.RECTANGLE, { x: ex, y: 1.15, w: 3.9, h: 0.42, fill: { color: C.primary } });
    slide.addText(src.title, {
      x: ex, y: 1.15, w: 3.9, h: 0.42,
      fontSize: 16, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
    });
    src.items.forEach((item, j) => {
      slide.addText(`· ${item}`, {
        x: ex + 0.1, y: 1.72 + j * 0.58, w: 3.7, h: 0.52,
        fontSize: 12, fontFace: "Microsoft YaHei", color: C.bodyText, margin: 0
      });
    });
  });

  // Error stats summary table
  slide.addText("误差统计汇总", {
    x: 0.6, y: 4.25, w: 4, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const eHdr = ["对比对象", "数据量", "误差范围", "平均误差", "评价"].map(t => makeTc(t, { hdr: true, fontSize: 12 }));
  const eRows = [
    ["实验 vs 预测", "31 组", "3.7%~46.8%", "12.52%", "可接受，极端参数偏差较大"],
    ["仿真 vs 预测", "12 组", "0.2%~0.5%", "~0.23%", "高度一致"],
    ["仿真 vs 实验", "12 组", "—", "趋势一致", "相互独立验证"],
  ].map((r, ri) => r.map(c => makeTc(c, { fill: ri % 2 === 0 ? C.cardBg : C.white, fontSize: 11 })));

  slide.addTable([eHdr, ...eRows], {
    x: 0.6, y: 4.6, w: 12.1, colW: [2.2, 1.3, 2.5, 2.0, 4.1],
    border: { pt: 0.5, color: C.separator },
    rowH: [0.35, 0.32, 0.32, 0.32],
  });

  // Overall assessment
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 5.95, w: 12.1, h: 0.85, fill: { color: C.cardBg } });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 5.95, w: 0.06, h: 0.85, fill: { color: C.accent } });
  slide.addText([
    { text: "综合评价", options: { bold: true, fontSize: 16, fontFace: "Microsoft YaHei", color: C.primary, breakLine: true } },
    { text: "理论-实验-仿真三者的误差均在可控范围内。理论模型捕捉了正确的物理规律（趋势100%一致），实验提供了可靠的标定数据（R²=0.971），仿真独立验证了模型的自洽性（偏差<0.5%）。极端参数区间（R_i=1cm, R_o/R_i≥6）的较大偏差主要源自空腔闭合模式的转变，提示了模型的适用范围边界。", options: { fontSize: 13, fontFace: "Microsoft YaHei", color: C.bodyText } },
  ], { x: 0.85, y: 6.0, w: 11.6, h: 0.75, valign: "middle", margin: 0 });
})();

// ============================================================
// S17: Conclusions
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "总  结", 18);

  const conclusions = [
    {
      num: "1",
      title: "建立了统一预测模型",
      detail: "基于能量守恒与空腔标度律，推导出 H_max = C·(R_o²−R_i²)/R_i³·H·sin²θ；通过 31 组实验数据拟合，确定 C = 1.203·(R_o/R_i)^(−0.287)·(H/R_i)^(−0.412)，R² = 0.971"
    },
    {
      num: "2",
      title: "系统揭示了参数影响规律",
      detail: "内径 R_i 是核心控制参数（三次方反比，降幅达 64%）；外径 R_o、释放高度 H、密度 ρ 呈正相关；环厚度 h 在 4-10mm 内为惰性参数；入水角度遵从 sin²θ 衰减规律"
    },
    {
      num: "3",
      title: "完成了三重验证闭环",
      detail: "理论推导（给出函数形式）→ 控制变量实验（确定参数值）→ COMSOL 仿真（独立验证趋势）→ 误差分析（理论/实验/仿真三维度），填补了环形结构入水问题的研究空白"
    },
  ];

  conclusions.forEach((c, i) => {
    const cy = 1.2 + i * 1.75;
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: cy, w: 0.7, h: 1.5, fill: { color: C.primary } });
    slide.addText(c.num, {
      x: 0.6, y: cy, w: 0.7, h: 1.5,
      fontSize: 36, fontFace: "Calibri", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
    });
    slide.addShape(pres.shapes.RECTANGLE, { x: 1.3, y: cy, w: 11.4, h: 1.5, fill: { color: C.cardBg } });
    slide.addShape(pres.shapes.RECTANGLE, { x: 1.3, y: cy, w: 11.4, h: 0.04, fill: { color: C.primary } });
    slide.addText(c.title, {
      x: 1.5, y: cy + 0.1, w: 11.0, h: 0.4,
      fontSize: 20, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
    });
    slide.addText(c.detail, {
      x: 1.5, y: cy + 0.55, w: 11.0, h: 0.85,
      fontSize: 14, fontFace: "Microsoft YaHei", color: C.bodyText, margin: 0
    });
  });

  slide.addShape(pres.shapes.RECTANGLE, { x: 0.8, y: 6.5, w: 11.7, h: 0.42, fill: { color: C.primary } });
  slide.addText("本研究为环形结构入水问题提供了完整的理论-实验-仿真框架，填补了该方向的研究空白", {
    x: 1.0, y: 6.5, w: 11.3, h: 0.42,
    fontSize: 14, fontFace: "Microsoft YaHei", color: C.white, bold: true, align: "center", valign: "middle", margin: 0
  });
})();

// ============================================================
// S18: Limitations & Future
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "局限性与未来展望", 19);

  // Limitations
  slide.addText("现有局限与改进方向", {
    x: 0.6, y: 1.15, w: 5, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const limitations = [
    "理论：射流半径简化为常数 → 引入动态半径模型",
    "理论：忽略附连水质量效应 → 需要定量修正项",
    "实验：500fps 帧率限制精度 (±1-2cm) → 升级至 2000+ fps",
    "实验：环释放角度偏差 (±3°) → 改进释放机构",
    "仿真：二维轴对称假设 → 开展三维 CFD 仿真",
    "仿真：忽略分子尺度耗散 → 引入湍流模型",
  ];
  addBulletList(slide, limitations, 0.6, 1.5, 7.2, 3.0, { fontSize: 13, color: C.bodyText });

  // Future
  slide.addText("后续研究方向", {
    x: 8.2, y: 1.15, w: 4.5, h: 0.3,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.primary, bold: true, margin: 0
  });

  const futures = [
    "建立环形结构入水的通用理论框架",
    "拓展至方形环、椭圆环等其他截面形状",
    "探索空腔闭合模式转变的临界判别准则",
    "开发\"环形喷泉参数设计软件\"",
    "将模型融入水鸟仿生推进的力学分析",
    "拓展至工业应用（环形炮口/喷嘴设计）",
  ];
  addBulletList(slide, futures, 8.2, 1.5, 4.5, 3.0, { fontSize: 13, color: C.bodyText });

  // Closing
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.8, y: 5.2, w: 11.7, h: 0.7, fill: { color: C.primary } });
  slide.addText([
    { text: "展望", options: { fontSize: 28, fontFace: "Microsoft YaHei", color: C.white, bold: true } },
    { text: "  ——  从单一扁平圆环出发，构建环形结构入水的通用理论框架，推动该方向从「现象描述」走向「定量预测」", options: { fontSize: 14, fontFace: "Microsoft YaHei", color: C.white } },
  ], { x: 1.0, y: 5.2, w: 11.3, h: 0.7, align: "center", valign: "middle", margin: 0 });

  // Innovation summary
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 6.1, w: 12.1, h: 0.7, fill: { color: C.cardBg } });
  slide.addText([
    { text: "创新点总结", options: { bold: true, fontSize: 16, fontFace: "Microsoft YaHei", color: C.primary, breakLine: true } },
    { text: "· 首次为环形结构入水建立了定量预测模型    · 识别了 R_i 的三次方反比这一核心标度律    · 实现了理论-实验-仿真三重独立验证的完整闭环", options: { fontSize: 13, fontFace: "Microsoft YaHei", color: C.bodyText } },
  ], { x: 0.8, y: 6.1, w: 11.7, h: 0.7, valign: "middle", margin: 0 });
})();

// ============================================================
// S19: References
// ============================================================
(() => {
  const slide = pres.addSlide();
  addStandardPage(slide, "参考文献", 20);

  const refs = [
    "[1] Akers B, Belmonte A. Impact dynamics of a solid sphere falling into a viscoelastic micellar fluid. J. Non-Newtonian Fluid Mech., 2006.",
    "[2] Truscott T T, Techet A H. A spin on cavity formation during water entry of hydrophobic and hydrophilic spheres. Phys. Fluids, 2009.",
    "[3] Aristoff J M, Bush J W M. Water entry of small hydrophobic spheres. J. Fluid Mech., 2010.",
    "[4] Gekle S, Gordillo J M. Generation and breakup of Worthington jets after cavity collapse. Part 1. Jet formation. J. Fluid Mech., 2010.",
    "[5] Glasheen J, McMahon T A. Vertical water entry of disks at low Froude numbers. Phys. Fluids, 1996.",
    "[6] Eggers J, Villermaux E. Physics of liquid jets. Rep. Prog. Phys., 2008.",
    "[7] Zeff B W, et al. Singularity dynamics in curvature collapse and jet eruption on a fluid surface. Nature, 2000.",
    "[8] 赵凯华, 罗蔚茵. 新概念物理教程·力学 (第2版). 高等教育出版社, 2002.",
  ];

  refs.forEach((ref, i) => {
    const ry = 1.2 + i * 0.65;
    slide.addText(ref, {
      x: 0.6, y: ry, w: 12.1, h: 0.5,
      fontSize: 14, fontFace: "Calibri", color: C.secondaryText, bold: true, valign: "middle", margin: 0
    });
    if (i < refs.length - 1) {
      slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: ry + 0.55, w: 12.1, h: 0.01, fill: { color: C.separator } });
    }
  });
})();

// ============================================================
// S20: Thank You
// ============================================================
(() => {
  const slide = pres.addSlide();
  slide.background = { color: C.white };
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.12, fill: { color: C.primary } });

  slide.addText("感谢各位老师聆听", {
    x: 0.5, y: 2.0, w: 12.3, h: 1.2,
    fontSize: 44, fontFace: "Microsoft YaHei", color: C.primary, bold: true, align: "center", valign: "middle", margin: 0
  });
  slide.addText("THANKS FOR YOUR ATTENTION", {
    x: 0.5, y: 3.1, w: 12.3, h: 0.6,
    fontSize: 20, fontFace: "Calibri", color: C.secondaryText, bold: true, align: "center", valign: "middle", margin: 0
  });
  slide.addShape(pres.shapes.RECTANGLE, { x: 4.5, y: 3.85, w: 4.3, h: 0.02, fill: { color: C.separator } });
  slide.addText("敬请各位老师批评指正", {
    x: 0.5, y: 4.0, w: 12.3, h: 0.8,
    fontSize: 18, fontFace: "Microsoft YaHei", color: C.bodyText, align: "center", valign: "middle", margin: 0
  });
  slide.addText("CUPT 2026 · Ring Fountain  |  西南交通大学  |  2026年5月", {
    x: 0.5, y: 5.5, w: 12.3, h: 0.5,
    fontSize: 12, fontFace: "Microsoft YaHei", color: C.bodyText, align: "center", valign: "middle", margin: 0
  });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 7.38, w: 13.3, h: 0.12, fill: { color: C.primary } });
})();

// ============================================================
pres.writeFile({ fileName: "D:\\cupt作品赛\\答辩PPT_环形喷泉.pptx" })
  .then(() => console.log("SUCCESS: D:\\cupt作品赛\\答辩PPT_环形喷泉.pptx"))
  .catch(err => console.error("ERROR:", err));
